"""Create initial schema.

Revision ID: cd8d7bce9a46
Revises: 8715a2997161
Create Date: 2025-12-20 23:44:06.778372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cd8d7bce9a46"
down_revision: Union[str, Sequence[str], None] = "8715a2997161"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# pylint: disable=no-member
# pylint: disable=too-many-statements
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_global_role",
        sa.Column("namespace", postgresql.CITEXT(length=64), nullable=False),
        sa.Column("name", postgresql.CITEXT(length=128), nullable=False),
        sa.Column("display_name", postgresql.CITEXT(length=128), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0",
            name="ck_global_role__display_name_nonempty",
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name="ck_global_role__name_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(namespace)) > 0", name="ck_global_role__namespace_nonempty"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "name", name="ux_global_role__namespace_name"),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_global_role_display_name"),
        "admin_global_role",
        ["display_name"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_permission_object",
        sa.Column("namespace", postgresql.CITEXT(length=64), nullable=False),
        sa.Column("name", postgresql.CITEXT(length=128), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name="ck_permission_object__name_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(namespace)) > 0",
            name="ck_permission_object__namespace_nonempty",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace", "name", name="ux_permission_object__namespace_name"
        ),
        schema="mugen",
    )
    op.create_table(
        "admin_permission_type",
        sa.Column("namespace", postgresql.CITEXT(length=64), nullable=False),
        sa.Column("name", postgresql.CITEXT(length=128), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name="ck_permission_type__name_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(namespace)) > 0",
            name="ck_permission_type__namespace_nonempty",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "namespace", "name", name="ux_permission_type__namespace_name"
        ),
        schema="mugen",
    )
    op.create_table(
        "admin_person",
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.CheckConstraint(
            "length(btrim(first_name)) > 0", name="ck_person__first_name_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(last_name)) > 0", name="ck_person__last_name_nonempty"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="mugen",
    )
    op.create_table(
        "admin_system_flag",
        sa.Column("namespace", postgresql.CITEXT(length=64), nullable=False),
        sa.Column("name", postgresql.CITEXT(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_set", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.CheckConstraint(
            "length(btrim(name)) > 0", name="ck_system_flag__name_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(namespace)) > 0", name="ck_system_flag__namespace_nonempty"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "name", name="ux_system_flag__namespace_name"),
        schema="mugen",
    )
    op.create_index(
        "ix_system_flag__namespace_name",
        "admin_system_flag",
        ["namespace", "name"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_global_permission_entry",
        sa.Column(
            "permitted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("permission_object_id", sa.Uuid(), nullable=False),
        sa.Column("permission_type_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("global_role_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["global_role_id"], ["mugen.admin_global_role.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["permission_object_id"],
            ["mugen.admin_permission_object.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_type_id"],
            ["mugen.admin_permission_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "global_role_id",
            "permission_object_id",
            "permission_type_id",
            name="ux_global_permission_entry__role_object_type",
        ),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_global_permission_entry_global_role_id"),
        "admin_global_permission_entry",
        ["global_role_id"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_user",
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_changed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("username", postgresql.CITEXT(length=128), nullable=False),
        sa.Column("login_email", postgresql.CITEXT(length=254), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "failed_login_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "NOT (deleted_at IS NOT NULL AND deleted_by_user_id IS NULL)",
            name="ck_user__not_deleted_and_not_deleted_by",
        ),
        sa.CheckConstraint(
            "NOT (locked_at IS NOT NULL AND locked_by_user_id IS NULL)",
            name="ck_user__not_locked_and_not_locked_by_user_id",
        ),
        sa.CheckConstraint(
            "NOT (password_changed_at IS NOT NULL AND password_changed_by_user_id IS"
            " NULL)",
            name="ck_user__not_password_changed_and_not_password_changed_by",
        ),
        sa.CheckConstraint(
            "failed_login_count >= 0", name="ck_user__failed_login_count_nonnegative"
        ),
        sa.CheckConstraint(
            "length(btrim(login_email)) > 0", name="ck_user__login_email_nonempty"
        ),
        sa.CheckConstraint(
            "length(btrim(username)) > 0", name="ck_user__username_nonempty"
        ),
        sa.CheckConstraint(
            "token_version >= 0", name="ck_user__token_version_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["deleted_by_user_id"],
            ["mugen.admin_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["locked_by_user_id"],
            ["mugen.admin_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["password_changed_by_user_id"],
            ["mugen.admin_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["mugen.admin_person.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_id", name="ux_user__person_id"),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_user_deleted_at"),
        "admin_user",
        ["deleted_at"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_user_last_login_at"),
        "admin_user",
        ["last_login_at"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_user_locked_at"),
        "admin_user",
        ["locked_at"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_user_login_email"),
        "admin_user",
        ["login_email"],
        unique=True,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_user_person_id"),
        "admin_user",
        ["person_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_user_username"),
        "admin_user",
        ["username"],
        unique=True,
        schema="mugen",
    )
    op.create_table(
        "admin_global_role_membership",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("global_role_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["global_role_id"], ["mugen.admin_global_role.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["mugen.admin_user.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "global_role_id", "user_id", name="ux_global_role_membership__role_user"
        ),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_global_role_membership_global_role_id"),
        "admin_global_role_membership",
        ["global_role_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_global_role_membership_user_id"),
        "admin_global_role_membership",
        ["user_id"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_refresh_token",
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("token_jti", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["mugen.admin_user.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_refresh_token_expires_at"),
        "admin_refresh_token",
        ["expires_at"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_refresh_token_token_hash"),
        "admin_refresh_token",
        ["token_hash"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_refresh_token_token_jti"),
        "admin_refresh_token",
        ["token_jti"],
        unique=True,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_refresh_token_user_id"),
        "admin_refresh_token",
        ["user_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        "ix_refresh_token__user_id_expires_at",
        "admin_refresh_token",
        ["user_id", "expires_at"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_tenant",
        sa.Column("name", postgresql.CITEXT(length=128), nullable=False),
        sa.Column("slug", postgresql.CITEXT(length=64), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("active", "suspended", name="admin_tenant_status"),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "NOT (deleted_at IS NOT NULL AND deleted_by_user_id IS NULL)",
            name="ck_tenant__not_deleted_and_not_deleted_by",
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name="ck_tenant__name_nonempty"),
        sa.CheckConstraint("length(btrim(slug)) > 0", name="ck_tenant__slug_nonempty"),
        sa.ForeignKeyConstraint(
            ["deleted_by_user_id"],
            ["mugen.admin_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_deleted_at"),
        "admin_tenant",
        ["deleted_at"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_status"),
        "admin_tenant",
        ["status"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_role",
        sa.Column("namespace", postgresql.CITEXT(length=64), nullable=False),
        sa.Column("name", postgresql.CITEXT(length=128), nullable=False),
        sa.Column("display_name", postgresql.CITEXT(length=128), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0", name="ck_role__display_name_nonempty"
        ),
        sa.CheckConstraint("length(btrim(name)) > 0", name="ck_role__name_nonempty"),
        sa.CheckConstraint(
            "length(btrim(namespace)) > 0", name="ck_role__namespace_nonempty"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["mugen.admin_tenant.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="ux_role__tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id", "namespace", "name", name="ux_role__tenant_namespace_name"
        ),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_role_display_name"),
        "admin_role",
        ["display_name"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_role_tenant_id"),
        "admin_role",
        ["tenant_id"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_tenant_domain",
        sa.Column("domain", postgresql.CITEXT(length=253), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "length(btrim(domain)) > 0", name="ck_tenant_domain__domain_nonempty"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["mugen.admin_tenant.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("domain"),
        sa.UniqueConstraint("tenant_id", "id", name="ux_tenant_domain__tenant_id_id"),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_domain_tenant_id"),
        "admin_tenant_domain",
        ["tenant_id"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_tenant_invitation",
        sa.Column("email", postgresql.CITEXT(length=254), nullable=False),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "accepted",
                "expired",
                "invited",
                "revoked",
                name="admin_tenant_invitation_status",
            ),
            server_default=sa.text("'invited'"),
            nullable=False,
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(status = 'accepted' AND accepted_at IS NOT NULL) OR (status <> 'accepted'"
            " AND accepted_at IS NULL)",
            name="ck_tenant_invitation__accepted_at_matches_status",
        ),
        sa.CheckConstraint(
            "(status = 'revoked' AND revoked_at IS NOT NULL) OR (status <> 'revoked'"
            " AND revoked_at IS NULL)",
            name="ck_tenant_invitation__revoked_at_matches_status",
        ),
        sa.CheckConstraint(
            "NOT (accepted_at IS NOT NULL AND revoked_at IS NOT NULL)",
            name="ck_tenant_invitation__not_accepted_and_revoked",
        ),
        sa.CheckConstraint(
            "length(btrim(email)) > 0", name="ck_tenant_invitation__email_nonempty"
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["mugen.admin_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["mugen.admin_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_user_id"],
            ["mugen.admin_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["mugen.admin_tenant.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "id", name="ux_tenant_invitation__tenant_id_id"
        ),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_invitation_email"),
        "admin_tenant_invitation",
        ["email"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_invitation_expires_at"),
        "admin_tenant_invitation",
        ["expires_at"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_invitation_status"),
        "admin_tenant_invitation",
        ["status"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_invitation_tenant_id"),
        "admin_tenant_invitation",
        ["tenant_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_invitation_token_hash"),
        "admin_tenant_invitation",
        ["token_hash"],
        unique=True,
        schema="mugen",
    )
    op.create_table(
        "admin_tenant_membership",
        sa.Column(
            "role_in_tenant",
            postgresql.ENUM(
                "admin", "member", "owner", name="admin_tenant_membership_role"
            ),
            server_default=sa.text("'member'"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active", "invited", "suspended", name="admin_tenant_membership_status"
            ),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["mugen.admin_tenant.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["mugen.admin_user.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "id", name="ux_tenant_membership__tenant_id_id"
        ),
        sa.UniqueConstraint(
            "tenant_id", "user_id", name="ux_tenant_membership__tenant_user"
        ),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_membership_role_in_tenant"),
        "admin_tenant_membership",
        ["role_in_tenant"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_membership_status"),
        "admin_tenant_membership",
        ["status"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_membership_tenant_id"),
        "admin_tenant_membership",
        ["tenant_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_tenant_membership_user_id"),
        "admin_tenant_membership",
        ["user_id"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_permission_entry",
        sa.Column(
            "permitted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("permission_object_id", sa.Uuid(), nullable=False),
        sa.Column("permission_type_id", sa.Uuid(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_object_id"],
            ["mugen.admin_permission_object.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_type_id"],
            ["mugen.admin_permission_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["mugen.admin_role.tenant_id", "mugen.admin_role.id"],
            name="fkx_permission_entry__tenant_role",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["mugen.admin_tenant.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "id", name="ux_permission_entry__tenant_id_id"
        ),
        sa.UniqueConstraint(
            "tenant_id",
            "role_id",
            "permission_object_id",
            "permission_type_id",
            name="ux_permission_entry__tenant_role_object_type",
        ),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_permission_entry_role_id"),
        "admin_permission_entry",
        ["role_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_permission_entry_tenant_id"),
        "admin_permission_entry",
        ["tenant_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        "ix_permission_entry__tenant_role",
        "admin_permission_entry",
        ["tenant_id", "role_id"],
        unique=False,
        schema="mugen",
    )
    op.create_table(
        "admin_role_membership",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "row_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "role_id"],
            ["mugen.admin_role.tenant_id", "mugen.admin_role.id"],
            name="fkx_role_membership__tenant_role",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "user_id"],
            [
                "mugen.admin_tenant_membership.tenant_id",
                "mugen.admin_tenant_membership.user_id",
            ],
            name="fkx_role_membership__tenant_user_membership",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["mugen.admin_tenant.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["mugen.admin_user.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="ux_role_membership__tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id",
            "role_id",
            "user_id",
            name="ux_role_membership__tenant_role_user",
        ),
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_role_membership_role_id"),
        "admin_role_membership",
        ["role_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_role_membership_tenant_id"),
        "admin_role_membership",
        ["tenant_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        op.f("ix_mugen_admin_role_membership_user_id"),
        "admin_role_membership",
        ["user_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        "ix_role_membership__tenant_role",
        "admin_role_membership",
        ["tenant_id", "role_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        "ix_role_membership__tenant_role_user",
        "admin_role_membership",
        ["tenant_id", "role_id", "user_id"],
        unique=False,
        schema="mugen",
    )
    op.create_index(
        "ix_role_membership__tenant_user",
        "admin_role_membership",
        ["tenant_id", "user_id"],
        unique=False,
        schema="mugen",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_role_membership__tenant_user",
        table_name="admin_role_membership",
        schema="mugen",
    )
    op.drop_index(
        "ix_role_membership__tenant_role_user",
        table_name="admin_role_membership",
        schema="mugen",
    )
    op.drop_index(
        "ix_role_membership__tenant_role",
        table_name="admin_role_membership",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_role_membership_user_id"),
        table_name="admin_role_membership",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_role_membership_tenant_id"),
        table_name="admin_role_membership",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_role_membership_role_id"),
        table_name="admin_role_membership",
        schema="mugen",
    )
    op.drop_table("admin_role_membership", schema="mugen")
    op.drop_index(
        "ix_permission_entry__tenant_role",
        table_name="admin_permission_entry",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_permission_entry_tenant_id"),
        table_name="admin_permission_entry",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_permission_entry_role_id"),
        table_name="admin_permission_entry",
        schema="mugen",
    )
    op.drop_table("admin_permission_entry", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_tenant_membership_user_id"),
        table_name="admin_tenant_membership",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_tenant_membership_tenant_id"),
        table_name="admin_tenant_membership",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_tenant_membership_status"),
        table_name="admin_tenant_membership",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_tenant_membership_role_in_tenant"),
        table_name="admin_tenant_membership",
        schema="mugen",
    )
    op.drop_table("admin_tenant_membership", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_tenant_invitation_token_hash"),
        table_name="admin_tenant_invitation",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_tenant_invitation_tenant_id"),
        table_name="admin_tenant_invitation",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_tenant_invitation_status"),
        table_name="admin_tenant_invitation",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_tenant_invitation_expires_at"),
        table_name="admin_tenant_invitation",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_tenant_invitation_email"),
        table_name="admin_tenant_invitation",
        schema="mugen",
    )
    op.drop_table("admin_tenant_invitation", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_tenant_domain_tenant_id"),
        table_name="admin_tenant_domain",
        schema="mugen",
    )
    op.drop_table("admin_tenant_domain", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_role_tenant_id"), table_name="admin_role", schema="mugen"
    )
    op.drop_index(
        op.f("ix_mugen_admin_role_display_name"),
        table_name="admin_role",
        schema="mugen",
    )
    op.drop_table("admin_role", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_tenant_status"), table_name="admin_tenant", schema="mugen"
    )
    op.drop_index(
        op.f("ix_mugen_admin_tenant_deleted_at"),
        table_name="admin_tenant",
        schema="mugen",
    )
    op.drop_table("admin_tenant", schema="mugen")
    op.drop_index(
        "ix_refresh_token__user_id_expires_at",
        table_name="admin_refresh_token",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_refresh_token_user_id"),
        table_name="admin_refresh_token",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_refresh_token_token_jti"),
        table_name="admin_refresh_token",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_refresh_token_token_hash"),
        table_name="admin_refresh_token",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_refresh_token_expires_at"),
        table_name="admin_refresh_token",
        schema="mugen",
    )
    op.drop_table("admin_refresh_token", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_global_role_membership_user_id"),
        table_name="admin_global_role_membership",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_global_role_membership_global_role_id"),
        table_name="admin_global_role_membership",
        schema="mugen",
    )
    op.drop_table("admin_global_role_membership", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_user_username"), table_name="admin_user", schema="mugen"
    )
    op.drop_index(
        op.f("ix_mugen_admin_user_person_id"), table_name="admin_user", schema="mugen"
    )
    op.drop_index(
        op.f("ix_mugen_admin_user_login_email"), table_name="admin_user", schema="mugen"
    )
    op.drop_index(
        op.f("ix_mugen_admin_user_locked_at"), table_name="admin_user", schema="mugen"
    )
    op.drop_index(
        op.f("ix_mugen_admin_user_last_login_at"),
        table_name="admin_user",
        schema="mugen",
    )
    op.drop_index(
        op.f("ix_mugen_admin_user_deleted_at"), table_name="admin_user", schema="mugen"
    )
    op.drop_table("admin_user", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_global_permission_entry_global_role_id"),
        table_name="admin_global_permission_entry",
        schema="mugen",
    )
    op.drop_table("admin_global_permission_entry", schema="mugen")
    op.drop_index(
        "ix_system_flag__namespace_name", table_name="admin_system_flag", schema="mugen"
    )
    op.drop_table("admin_system_flag", schema="mugen")
    op.drop_table("admin_person", schema="mugen")
    op.drop_table("admin_permission_type", schema="mugen")
    op.drop_table("admin_permission_object", schema="mugen")
    op.drop_index(
        op.f("ix_mugen_admin_global_role_display_name"),
        table_name="admin_global_role",
        schema="mugen",
    )
    op.drop_table("admin_global_role", schema="mugen")

    # Drop enums last (after all referencing tables are gone).
    op.execute("DROP TYPE IF EXISTS mugen.admin_tenant_membership_role")
    op.execute("DROP TYPE IF EXISTS mugen.admin_tenant_membership_status")
    op.execute("DROP TYPE IF EXISTS mugen.admin_tenant_invitation_status")
    op.execute("DROP TYPE IF EXISTS mugen.admin_tenant_status")
    # ### end Alembic commands ###
